# Tema
theme = "catppuccin_mocha"

# Features
[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.indent-guides]
render = true

[editor.statusline]
left = [
    "mode",
    "spacer",
    "version-control",
    "spacer",
    "spinner",
    "read-only-indicator",
]
center = ["file-name", "file-modification-indicator"]
right = [
    "diagnostics",
    "selections",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = " "
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

# Soft-Wrap
[editor.soft-wrap]
enable = true
wrap-indicator = "â†ª "
max-indent-retain = 40
max-wrap = 20
